# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_entry.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_table_entry_frame(object):
    def setupUi(self, table_entry_frame):
        table_entry_frame.setObjectName("table_entry_frame")
        table_entry_frame.resize(799, 40)
        table_entry_frame.setMaximumSize(QtCore.QSize(16777215, 42))
        self.horizontalLayout = QtWidgets.QHBoxLayout(table_entry_frame)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(table_entry_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.character_name = QtWidgets.QLabel(self.frame)
        self.character_name.setObjectName("character_name")
        self.horizontalLayout_2.addWidget(self.character_name)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.skill_value_label = QtWidgets.QLabel(self.frame)
        self.skill_value_label.setText("")
        self.skill_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_value_label.setObjectName("skill_value_label")
        self.horizontalLayout_2.addWidget(self.skill_value_label)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.roll_label = QtWidgets.QLabel(self.frame)
        self.roll_label.setText("")
        self.roll_label.setAlignment(QtCore.Qt.AlignCenter)
        self.roll_label.setObjectName("roll_label")
        self.horizontalLayout_2.addWidget(self.roll_label)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.ps_label = QtWidgets.QLabel(self.frame)
        self.ps_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ps_label.setText("")
        self.ps_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ps_label.setObjectName("ps_label")
        self.horizontalLayout_2.addWidget(self.ps_label)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(table_entry_frame)
        QtCore.QMetaObject.connectSlotsByName(table_entry_frame)

    def retranslateUi(self, table_entry_frame):
        _translate = QtCore.QCoreApplication.translate
        table_entry_frame.setWindowTitle(_translate("table_entry_frame", "Form"))
        self.character_name.setText(_translate("table_entry_frame", "TextLabel"))
