# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_entry.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(874, 40)
        Form.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.entry_name = QtWidgets.QCheckBox(Form)
        self.entry_name.setObjectName("entry_name")
        self.horizontalLayout.addWidget(self.entry_name)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.skill_value_label = QtWidgets.QLabel(Form)
        self.skill_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_value_label.setObjectName("skill_value_label")
        self.horizontalLayout.addWidget(self.skill_value_label)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.roll_label = QtWidgets.QLabel(Form)
        self.roll_label.setText("")
        self.roll_label.setAlignment(QtCore.Qt.AlignCenter)
        self.roll_label.setObjectName("roll_label")
        self.horizontalLayout.addWidget(self.roll_label)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.ps_label = QtWidgets.QLabel(Form)
        self.ps_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ps_label.setText("")
        self.ps_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ps_label.setObjectName("ps_label")
        self.horizontalLayout.addWidget(self.ps_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.entry_name.setText(_translate("Form", "CheckBox"))
        self.skill_value_label.setText(_translate("Form", "TextLabel"))
