ATTRIBUTES = [
    'Weapon Skill',
    'Ballistic Skill',
    'Strength',
    'Toughness',
    'Initiative',
    'Agility',
    'Dexterity',
    'Intelligence',
    'Willpower',
    'Fellowship'
]

BASIC_SKILLS = [
    'Art',
    'Athletics',
    'Bribery',
    'Charm',
    'Animal',
    'Climb',
    'Cool',
    'Consume',
    'Alcohol',
    'Dodge',
    'Drive',
    'Endurance',
    'Entertain',
    'Gamble',
    'Gossip',
    'Haggle',
    'Intimidate',
    'Intuition',
    'Leadership',
    'Melee',
    'Navigation',
    'Outdoor Survival',
    'Perception',
    'Ride',
    'Row',
    'Stealth'
]

ADVANCED_SKILLS = [
    'Animal Care',
    'Animal Training',
    'Channelling',
    'Evaluate',
    'Heal',
    'Language',
    'Lore',
    'Perform',
    'Pick Lock',
    'Play',
    'Pray',
    'Ranged',
    'Research',
    'Sail',
    'Secret Signs',
    'Set Trap',
    'Sleight of Hand',
    'Swim',
    'Track',
    'Trade'
]
