# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'advanced_skill_entry.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_advanced_skill_entry(object):
    def setupUi(self, advanced_skill_entry):
        advanced_skill_entry.setObjectName("advanced_skill_entry")
        advanced_skill_entry.resize(94, 64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(advanced_skill_entry.sizePolicy().hasHeightForWidth())
        advanced_skill_entry.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(advanced_skill_entry)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(advanced_skill_entry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.advanced_skill_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advanced_skill_label.sizePolicy().hasHeightForWidth())
        self.advanced_skill_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.advanced_skill_label.setFont(font)
        self.advanced_skill_label.setAlignment(QtCore.Qt.AlignCenter)
        self.advanced_skill_label.setObjectName("advanced_skill_label")
        self.verticalLayout_2.addWidget(self.advanced_skill_label)
        self.advanced_skill_value = QtWidgets.QSpinBox(self.frame)
        self.advanced_skill_value.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advanced_skill_value.sizePolicy().hasHeightForWidth())
        self.advanced_skill_value.setSizePolicy(sizePolicy)
        self.advanced_skill_value.setMinimumSize(QtCore.QSize(80, 0))
        self.advanced_skill_value.setMaximum(500)
        self.advanced_skill_value.setObjectName("advanced_skill_value")
        self.verticalLayout_2.addWidget(self.advanced_skill_value)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(advanced_skill_entry)
        QtCore.QMetaObject.connectSlotsByName(advanced_skill_entry)

    def retranslateUi(self, advanced_skill_entry):
        _translate = QtCore.QCoreApplication.translate
        advanced_skill_entry.setWindowTitle(_translate("advanced_skill_entry", "Form"))
        self.advanced_skill_label.setText(_translate("advanced_skill_entry", "TextLabel"))
